name: Scrape Cloudflare IPs

on:
  schedule:
    - cron: '*/10 * * * *'  # Run every 10 minutes
  workflow_dispatch:  # Allow manual triggering
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4
    
    - name: Run scraper
      run: 
        python cloudflare_ip_scraper.py
    
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add .
        git commit -m "Update Cloudflare IPs $(date +'%Y-%m-%d %H:%M:%S')"
        git push
